=== ariana9rande/2022-Web-EXs/ch04/BookCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://cs.skuniv.ac.kr/xml/hjh"
		xmlns:target="http://cs.skuniv.ac.kr/xml/hjh"
		elementFormDefault="qualified">
	<element name="BookCatalog">
		<complexType>
			<sequence>
				<element name="Book" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="Title" type="string"/>
							<element name="Author" type="string"/>
							<element name="Year" type="string"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== ariana9rande/2022-Web-EXs/ch04/BookCatalog.xml
<?xml version="1.0"?>
<BookCatalog xmlns="http://cs.skuniv.ac.kr/xml/hjh"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://cs.skuniv.ac.kr/xml/hjh BookCatalog.xsd">
	<Book>
		<Title>title1</Title>
		<Author>author1</Author>
		<Year>2022</Year>
	</Book>
	<Book>
		<Title>title2</Title>
		<Author>author2</Author>
		<Year>2021</Year>
	</Book>
	<Book>
		<Title>title3</Title>
		<Author>author3</Author>
		<Year>2020</Year>
	</Book>
</BookCatalog>
