=== ariana9rande/2022-Web-EXs/ch04/ex4-7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://cs.skuniv.ac.kr/xml/hjh"
		xmlns:target="http://cs.skuniv.ac.kr/xml/hjh"
		elementFormDefault="qualified">

	<simpleType name="hourScope">
		<restriction base="int">
			<minInclusive value="0"/>
			<maxExclusive value="10"/>
		</restriction>
	</simpleType>
	<simpleType name="minuteScope">
		<restriction base="int">
			<minInclusive value="0"/>
			<maxExclusive value="60"/>
		</restriction>
	</simpleType>
	<simpleType name="secondScope">
		<restriction base="int">
			<minInclusive value="0"/>
			<maxExclusive value="60"/>
		</restriction>
	</simpleType>

	<element name="Song">
		<complexType mixed="true">
			<sequence>
				<element name="playTime">
					<complexType>
						<sequence>
							<element name="hours" type="target:hourScope"/>
							<element name="minutes" type="target:minuteScope"/>
							<element name="seconds" type="target:secondScope"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

	<group name="AlbumGroup">
		<sequence>
			<element name="Title" type="string"/>
			<element name="Artist" type="string"/>
			<element name="Genre" type="string"/>
			<element name="Released-date" type="string"/>
			<element ref="target:Song" maxOccurs="unbounded"/>
		</sequence>
	</group>

	<element name="AudioCatalog">
		<complexType>
			<choice maxOccurs="unbounded">
				<element name="Cd">
					<complexType>
						<group ref="target:AlbumGroup"/>
					</complexType>
				</element>
				<element name="Record">
					<complexType>
						<group ref="target:AlbumGroup"/>
					</complexType>
				</element>
				<element name="Mp3">
					<complexType>
						<group ref="target:AlbumGroup"/>
					</complexType>
				</element>
			</choice>
		</complexType>
	</element>
</schema>

=== ariana9rande/2022-Web-EXs/ch04/ex4-7.xml
<?xml version="1.0" encoding="utf-8"?>
<AudioCatalog xmlns="http://cs.skuniv.ac.kr/xml/hjh"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cs.skuniv.ac.kr/xml/hjh ex4-7.xsd">
	<Cd>
		<Title>Yours Truly</Title>
		<Artist>Ariana Grande</Artist>
		<Genre>Pop</Genre>
		<Released-date>2013/09/02</Released-date>
		<Song>
			Honeymoon Avenue
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
		<Song>
			Lovin' It
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
		<Song>
			The Way
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
	</Cd>
	<Record>
		<Title>My Everything</Title>
		<Artist>Ariana Grande</Artist>
		<Genre>Pop</Genre>
		<Released-date>2014/08/25</Released-date>
		<Song>
			Why Try
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
		<Song>
			Best Mistake
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
		<Song>
			Be My Baby
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
	</Record>
	<Mp3>
		<Title>Dangerous Woman</Title>
		<Artist>Ariana Grande</Artist>
		<Genre>Pop</Genre>
		<Released-date>2016/04/01</Released-date>
		<Song>
			Moonlight
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
		<Song>
			Touch It
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
		<Song>
			Thinking Bout You
			<playTime>
				<hours>0</hours>
				<minutes>3</minutes>
				<seconds>30</seconds>
			</playTime>
		</Song>
	</Mp3>
</AudioCatalog>
